name: automerge
on:
  workflow_run:
    workflows: ["Auto-Merge Bot"]
    types: [completed]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          LOG: "TRACE"
