name: Status Change
on: status
jobs:
  event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event data
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
